print("My name is Riley")
print("Erin is slow")
print("shut up riley")
print("I was born in December")
print("My favorite food is ice cream")
print("my favorite type of music is good music")
print("my sign is capricorn")
