print("My name is Riley")
print("Erin is slow")
print("shut up riley")
print("I was born in December")
print("my favorite food is steak")
print("My favorite type of music is gospel rap")
print("Mr sign is Aries")
print("My favorite food is ice cream")
print("my favorite type of music is good music")
print("my sign is capricorn")
